import React from "react";
import MainBanner from "../Speakers/MainBanner";
import OtherFooter from "../Common/OtherFooter";
import NewSpeakers from "../HomeTwo/NewSpeakers";

const SpeakersAmsLegal = () => {
  const cardData = [
    {
      name: "James Hall",
      desg: "CEO, Founder and General Counsel",
      company: "Global GC",
      country: "USA",
      image: "/images/James Hall.jpg",
      linkedIn: "https://www.linkedin.com/in/james-hall-98868a7/",
    },
    {
      name: "Dr Rob Vossen",
      desg: " Director",
      company: "CEG - Competition Economists Group",
      country: "Netherlands",
      image: "/images/Rob_Vossen.jpg",
      linkedIn: "https://www.linkedin.com/in/rob-vossen-871945a/",
    },
    {
      name: "Gary Brown",
      desg: " Chief Privacy Officer",
      company: "Westinghouse Electric Company",
      country: "United Kingdom",
      image: "/images/a-l-speaker85.jpg",
      linkedIn: "https://www.linkedin.com/in/gary-brown-37212621/",
    },
    {
      name: "Eoin Cunneen",
      desg: "Partner",
      company: "Flynn O'Driscoll LLP",
      country: "Ireland",
      image: "/images/Eoin_Cunneen.jpg",
      linkedIn: "https://www.linkedin.com/in/eoincunneen/",
    },
    {
      name: "David Curran",
      desg: "Partner",
      company: " Flynn O'Driscoll LLP",
      country: "Ireland",
      image: "/images/David_Curran.jpg",
      linkedIn: "https://www.linkedin.com/in/david-curran-94197b77/",
    },
    {
      name: "Joseph Benkel",
      desg: " Partner",
      company: "Shibolet. Law Firm",
      country: "Israel",
      image: "/images/a-l-speaker88.png",
      linkedIn: "https://www.shibolet.com/en/team/joseph-benkel/",
    },
    {
      name: "Sabrina Strassburger",
      desg: "Compliance Officer",
      company: "Damen",
      country: "Netherlands",
      image: "/images/a-l-speaker34.png",
      linkedIn:
        "https://www.linkedin.com/in/sabrina-strassburger-ph-d-29653a37/",
    },
    {
      name: "Ashraf Motei",
      desg: "Founder/Managing Partner",
      company: "Motei & Associates",
      country: "UAE",
      image: "/images/a-l-speaker30.jpg",
      linkedIn: "https://www.linkedin.com/in/ashrafmotei/",
    },
    {
      name: "Ayman Al-Wadi",
      desg: "Group Executive Chairman",
      company: "AW HOLDING INT'L",
      country: "UAE",
      image: "/images/a-l-speaker29.jpg",
      linkedIn: "https://www.linkedin.com/in/ayman-al-wadi/",
    },
    {
      name: "Mirjam Ros",
      desg: "Author",
      company: "The Innovation Matrix",
      country: "Netherlands",
      image: "/images/a-l-speaker28.jpg",
      linkedIn: "https://www.linkedin.com/in/mirjamros/",
    },
    {
      name: "Alejandro Llosa",
      desg: "Senior Legal Counsel ",
      company: "Accenture",
      country: "Ireland",
      image: "/images/a-l-speaker27.jpg",
      linkedIn: "https://www.linkedin.com/in/alejandrollosa/",
    },
    {
      name: "Ahmed Afifi",
      desg: "Senior Commercial Manager",
      company: "",
      country: "KSA",
      image: "/images/a-l-speaker26.jpg",
      linkedIn: "https://www.linkedin.com/in/ahmed-afifi-90501b26/",
    },
    {
      name: "Irith Kist",
      desg: "Data Protection Officer",
      company: "The Netherlands Cancer Institute",
      country: "Netherlands",
      image: "/images/a-l-speaker25.jpg",
      linkedIn: "https://www.linkedin.com/in/irith-kist-9727769/",
    },
    {
      name: "Jan McSweeney",
      desg: "Member (Professor Wolfgang Kraft PhD)",
      company: "The United Nations international taxation experts",
      country: "Australia",
      image: "/images/a-l-speaker24.jpg",
      linkedIn: "https://www.linkedin.com/in/jpsmstorytime/",
    },
    {
      name: "Tatevik S. Karapetyan, PhD",
      desg: "Senior Researcher ",
      company: "Fondazione Giorgio Cini Onlus, Venice",
      country: "Armenia",
      image: "/images/a-l-speaker23.JPG",
      linkedIn: "https://www.linkedin.com/in/tatev-s-karapetyan-phd-35aa82200/",
    },
    {
      name: "Carlos Landazabal Angeli ",
      desg: "Compliance & Data Protection Officer",
      company: "Canadian Solar Inc",
      country: "Spain",
      image: "/images/a-l-speaker22.jpg",
      linkedIn: "https://www.linkedin.com/in/clandazabal/",
    },
    {
      name: "Sukla Chandra",
      desg: "Senior Managing Director",
      company: "GE",
      country: "India",
      image: "/images/a-l-speaker20.png",
      linkedIn: "https://www.linkedin.com/in/sukla-chandra-84a8ba13/",
    },
    {
      name: "Ray Lei ZHAO, LL.M",
      desg: "Senior Partner",
      company: "Unitalen Attorneys at Law ",
      country: "China",
      image: "/images/a-l-speaker19.jpg",
      linkedIn: "https://www.linkedin.com/in/ray-lei-zhao-ll-m-08621a62/",
    },
    {
      name: "R Rishi",
      desg: "Founder & Principal",
      company: "Rishi & Partners",
      country: "Malaysia",
      image: "/images/a-l-speaker18.jpeg",
      linkedIn:
        "https://www.linkedin.com/in/r-rishi-%E7%91%9E%E7%86%99-9a351510/",
    },
    {
      name: "Onur Korucu",
      desg: "Vice President",
      company: "TerzionDx",
      country: "Ireland",
      image: "/images/a-l-speaker17.png",
      linkedIn: "https://www.linkedin.com/in/onur-korucu-73a9b47b/",
    },
    {
      name: "Mahmoud Shaarawy",
      desg: "Chief Legal and Compliance Officer",
      company: "HSA Group",
      country: "Egypt",
      image: "/images/a-l-speaker16.jpg",
      linkedIn: "https://www.linkedin.com/in/shaarawy/",
    },
    {
      name: "Ashok Venkateshmurthy",
      desg: "Partner",
      company: "Factum Law",
      country: "India",
      image: "/images/a-l-speaker15.jpg",
      linkedIn: "https://www.linkedin.com/in/ashokgv/",
    },
    {
      name: "Rajesh Ramanathan",
      desg: "Partner",
      company: "Factum Law",
      country: "India",
      image: "/images/a-l-speaker14.jpg",
      linkedIn: "https://www.linkedin.com/in/rajesh-ramanathan-5b87191/",
    },

    {
      name: "Chucks Obi",
      desg: "Compliance Professional",
      company: "",
      country: "Netherlands",
      image: "/images/a-l-speaker13.jpg",
      linkedIn: "https://www.linkedin.com/in/chucks-obi-5227389b/",
    },
    {
      name: "Linda Mouaz",
      desg: "General Counsel",
      company: "Nestlé",
      country: "UAE",
      image: "/images/a-l-speaker12.jpg",
      linkedIn: " https://www.linkedin.com/in/linda-mouaz-93a11a119/",
    },
    {
      name: "Adrian Cole",
      desg: "  Board Member",
      company: "Adrian Cole FZ LLE",
      country: "UAE",
      image: "/images/speaker42.png",
      linkedIn:
        "https://www.linkedin.com/in/adrian-cole-b1a3ba5/?originalSubdomain=ae",
    },
    {
      name: "Yoav Salomon",
      desg: "Managing Partner",
      company: "Avniel, Salomon & Co ",
      country: "Israel ",
      image: "/images/speaker33.png",
      linkedIn: "https://www.linkedin.com/in/yoavsalomon/",
    },
    {
      name: "Galina Lyubcheva ",
      desg: "Legal Counsel ",
      company: "OpenPayd ",
      country: "Bulgaria ",
      image: "/images/a-l-speaker11.jpeg",
      linkedIn: "https://www.linkedin.com/in/galina-lyubcheva-7b9b8a52/",
    },
    {
      name: "Sameet Gambhir",
      desg: "Vice President (Corp. Law) & Company Secretary ",
      company: " DCM Shriram Ltd",
      country: "India",
      image: "/images/speaker8.jpg",
      linkedIn: " https://www.linkedin.com/in/sameet-gambhir-0107133/",
    },
    {
      name: "Pavle Bojkovski",
      desg: "Senior Commercial Legal Counsel",
      company: "Accenture",
      country: "Netherlands",
      image: "/images/a-l-speaker10.jpg",
      linkedIn: " https://www.linkedin.com/in/pavlebojkovski/",
    },
    {
      name: "Ahmad Saleh",
      desg: "Partner",
      company: "Al Tamimi & Company",
      country: "UAE",
      image: "/images/a-l-speaker9.jpg",
      linkedIn: " https://www.linkedin.com/in/salehip/",
    },
    {
      name: "Beatriz Ruiz-Beato",
      desg: "Global Head of Data Privacy",
      company: "NEC Corporation",
      country: "Spain",
      image: "/images/a-l-speaker8.jpg",
      linkedIn: " https://www.linkedin.com/in/beatrizruizbeato/",
    },
    {
      name: "John Giannakakis ",
      desg: "Senior Partner",
      company: "Hellenic Ministry of Migration and Asylum ",
      country: "Greece",
      image: "/images/a-l-speaker7.png",
      linkedIn: "https://www.linkedin.com/in/johngiannakakis/",
    },
    {
      name: "Berardino Tizzani",
      desg: "Legal Counsel",
      company: "NewCold",
      country: "Netherlands",
      image: "/images/a-l-speaker6.jpg",
      linkedIn: "https://www.linkedin.com/in/berardino-tizzani/",
    },
    {
      name: "Richard Milchior",
      desg: "Partner ",
      company: "Herald",
      country: "France",
      image: "/images/a-l-speaker5.jpg",
      linkedIn: "https://www.linkedin.com/in/richard-milchior/",
    },
    {
      name: "Ozan Akyurek",
      desg: "Partner ",
      company: "Jones Day",
      country: "France",
      image: "/images/a-l-speaker4.jpg",
      linkedIn: "https://www.linkedin.com/in/ozan-akyurek-6a22281/",
    },
    {
      name: " Renata Berzanskiene",
      desg: "General Counsel ",
      company: "ORLEN Lietuva, AB ",
      country: "Lithuania",
      image: "/images/a-l-speaker3.jpg",
      linkedIn: " https://www.linkedin.com/in/renata-berzanskiene-3363773/",
    },
    {
      name: "Dilara Kasapoğlu",
      desg: "Corporate Counsel ",
      company: " ",
      country: "Netherlands",
      image: "/images/a-l-speaker2.jpg",
      linkedIn: " https://www.linkedin.com/in/dilara-k/",
    },
    {
      name: "Nicolas Demigneux",
      desg: "Managing Partner ",
      company: "Stephenson Harwood",
      country: "France",
      image: "/images/speaker27.png",
      linkedIn: "https://www.linkedin.com/in/nicolas-demigneux-7181122/",
    },
    {
      name: "John Shehata, MSc, PhD ",
      desg: "Lawyer and Professional Faculty Member",
      company: "SDA Bocconi School of Management",
      country: "Italy",
      image: "/images/speaker47.png",
      linkedIn: " https://www.linkedin.com/in/jshehata/",
    },
    {
      name: "Dr. Dimitrios Athanasakis",
      desg: "Vice President Legal",
      company: "Hill International, Inc.",
      country: "Netherlands",
      image: "/images/a-l-speaker1.png",
      linkedIn: " https://www.linkedin.com/in/athanasakis-legalcounsel/",
    },
  ];
  return (
    <React.Fragment>
      <MainBanner
        heading="Speakers - GLA  Litigation Amsterdam"
        lastLine="Speakers"
      />
      <NewSpeakers cardData={cardData} />
      <OtherFooter />
    </React.Fragment>
  );
};

export default SpeakersAmsLegal;
